[2023-05-24T13:04:56.433+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: docker-dag.insert_execution_time manual__2023-05-24T13:04:55.087429+00:00 [queued]>
[2023-05-24T13:04:56.441+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: docker-dag.insert_execution_time manual__2023-05-24T13:04:55.087429+00:00 [queued]>
[2023-05-24T13:04:56.441+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T13:04:56.442+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-24T13:04:56.442+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T13:04:56.452+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_execution_time> on 2023-05-24 13:04:55.087429+00:00
[2023-05-24T13:04:56.458+0000] {standard_task_runner.py:55} INFO - Started process 2694 to run task
[2023-05-24T13:04:56.464+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'docker-dag', 'insert_execution_time', 'manual__2023-05-24T13:04:55.087429+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/docker-task.py', '--cfg-path', '/tmp/tmpcqfng66u']
[2023-05-24T13:04:56.472+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask insert_execution_time
[2023-05-24T13:04:56.545+0000] {task_command.py:388} INFO - Running <TaskInstance: docker-dag.insert_execution_time manual__2023-05-24T13:04:55.087429+00:00 [running]> on host fe8636e26e35
[2023-05-24T13:04:56.593+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker-dag
AIRFLOW_CTX_TASK_ID=insert_execution_time
AIRFLOW_CTX_EXECUTION_DATE=2023-05-24T13:04:55.087429+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-24T13:04:55.087429+00:00
[2023-05-24T13:04:56.594+0000] {sql.py:254} INFO - Executing: INSERT INTO test (time) VALUES (%s);
[2023-05-24T13:04:56.602+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-24T13:04:56.718+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-24T13:04:56.724+0000] {sql.py:375} INFO - Running statement: INSERT INTO test (time) VALUES (%s);, parameters: ['2023-05-24 13:04:56.328127']
[2023-05-24T13:04:56.726+0000] {sql.py:384} INFO - Rows affected: 1
[2023-05-24T13:04:56.736+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=docker-dag, task_id=insert_execution_time, execution_date=20230524T130455, start_date=20230524T130456, end_date=20230524T130456
[2023-05-24T13:04:56.764+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-05-24T13:04:56.782+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
